title: Franzininho
email: your-email@example.com
description:
baseurl: ""
url: https://allythy.github.io/teste
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
